### ISSUE TITLE
Access to Contacts

### ISSUE THREAD

**Issue by freshyill** [brunosimon/keppler#42]
I'd like to test Keppler, but it's requesting access to my Contacts before it even launches in the browser. I denied access and now it won't even launch.

Why does this want to scan my contacts?

```
---------------------- keppler 1.4.3 ----------------------

app > config - debug - 1
app > config - name - Testing
app > config - port - 1571
app > config - exclude - **/.DS_Store,**/node_modules/**,**/vendor/**,**/.git,**/.vscode,**/.env,**/.log,.idea/**,**/*___jb_old___,**/*___jb_tmp___
app > config - open - true
app > config - test - false
app > config - limit - 99
app > config - maxFileSize - 99999
app > config - server - false
app > config - host - false
app > config - domain - http://192.168.7.108:1571
/Users/coleman/.nvm/versions/node/v12.9.0/lib/node_modules/keppler/node_modules/glob/sync.js:341
        throw er
        ^

Error: EPERM: operation not permitted, scandir '/Users/coleman/Library/Application Support/AddressBook'
    at Object.readdirSync (fs.js:837:3)
    at GlobSync._readdir (/Users/coleman/.nvm/versions/node/v12.9.0/lib/node_modules/keppler/node_modules/glob/sync.js:288:41)
    at GlobSync._readdirInGlobStar (/Users/coleman/.nvm/versions/node/v12.9.0/lib/node_modules/keppler/node_modules/glob/sync.js:267:20)
    at GlobSync._readdir (/Users/coleman/.nvm/versions/node/v12.9.0/lib/node_modules/keppler/node_modules/glob/sync.js:276:17)
    at GlobSync._processGlobStar (/Users/coleman/.nvm/versions/node/v12.9.0/lib/node_modules/keppler/node_modules/glob/sync.js:350:22)
    at GlobSync._process (/Users/coleman/.nvm/versions/node/v12.9.0/lib/node_modules/keppler/node_modules/glob/sync.js:130:10)
    at GlobSync._processGlobStar (/Users/coleman/.nvm/versions/node/v12.9.0/lib/node_modules/keppler/node_modules/glob/sync.js:383:10)
    at GlobSync._process (/Users/coleman/.nvm/versions/node/v12.9.0/lib/node_modules/keppler/node_modules/glob/sync.js:130:10)
    at GlobSync._processGlobStar (/Users/coleman/.nvm/versions/node/v12.9.0/lib/node_modules/keppler/node_modules/glob/sync.js:383:10)
    at GlobSync._process (/Users/coleman/.nvm/versions/node/v12.9.0/lib/node_modules/keppler/node_modules/glob/sync.js:130:10) {
  errno: -1,
  syscall: 'scandir',
  code: 'EPERM',
  path: '/Users/coleman/Library/Application Support/AddressBook'
}
 ✘ coleman@ChristopherColemanMacBookPro  ~  
```

**Comment by makew0rld** [comment]
Are you running it from a directory that contains the Address book?
