### ISSUE TITLE
Cannot read properties of null (reading 'files')

### ISSUE THREAD

**Issue by melvinlemoine** [brunosimon/keppler#69]
Hello there !

I tried for the first time to launch server and connection to  to with my laptop. When I launch the server before I try to connect , this error spawn (crash).
But when I launch the server after launch keppler on my laptop not problem.

<img width="596" alt="Capture d’écran 2022-12-01 à 13 21 31" src="https://user-images.githubusercontent.com/23276163/205054186-45a03f3b-2937-4d63-8756-debc99ad8ed6.png">

**Comment by amantank** [comment]
Just add the ? before the .files in the path specified. 
Example:   `project?.files.create(data.path, data.content)`

**Comment by Docusland** [comment]
Same issue here, if I launch the server first, it crashes while the client connects : 
```sh
/usr/local/lib/node_modules/keppler/lib/index.js:267
                project.files.create(data.path, data.content)
                        ^

TypeError: Cannot read properties of null (reading 'files')
    at Socket.<anonymous> (/usr/local/lib/node_modules/keppler/lib/index.js:267:25)
    at Socket.emit (node:events:513:28)
    at /usr/local/lib/node_modules/keppler/node_modules/socket.io/lib/socket.js:531:14
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.16.0

```
amantank's solution fails as otherwise it just crashes on line 268. 
Yet launching the server after the client's launch works fine. Even though the first file sync fails and files wait to be modified for a proper sync.
